export const ch13 = {
  id: "miller_ch13",
  chapterNumber: 13,
  title: "Cardiac Physiology",
  bookId: "miller",
  readTimeMinutes: 29,
  sections: [
    {
      title: `Section 1`,
      content: `ANESTHESIA BOARD REVIEW & STUDY`
    },
    {
      title: `GUIDE`,
      content: `HIGH-YIELD COMPREHENSIVE SUMMARY: CARDIAC PHYSIOLOGY ONLY
Section 1: Macro Architecture & Circulation
The basic anatomy of the heart consists of two atria and two ventricles that provide two separate circulations
arranged in series [source: 14]. The pulmonary circulation is a low-resistance, high-capacitance vascular bed that
receives output from the right side of the heart; its primary function is bidirectional gas exchange [source: 15]. The
left side of the heart provides output for the systemic circulation, which functions to deliver oxygen (O₂) and
nutrients to tissue beds and remove carbon dioxide (CO₂) and metabolic waste products [source: 16, 17].
Section 2: The Cardiac Cycle: Electrical & Mechanical Coordination
The cardiac cycle is defined as the precise sequence of electrical and mechanical events taking place during a
single  heartbeat  [source:  1,  19].  Automaticity  and  rhythmicity  are  intrinsic  properties  of  specialized  cardiac
pacemaker tissue [source: 21]. The cycle is initiated by spontaneous impulse generation at the sinoatrial (SA) node,
which acts as the natural pacemaker due to having the highest intrinsic firing frequency [source: 22, 23].
Electrical Propagation Timeline & Electrocardiogram (ECG) Correlations:
P Wave: Represents atrial depolarization initiated at the SA node and propagated through specialized atrial
conduction tissue, leading directly to atrial systole [source: 26].
PR Interval: Corresponds to the physiological delay that occurs at the atrioventricular (AV) node [source: 29].
The AV node is characterized by relatively slow conduction velocity, ensuring optimal ventricular filling before
ventricular contraction begins [source: 28].
QRS Complex: Reflects the rapid spread of depolarization through the specialized ventricular conduction
system—converging from the distal His bundle into the large left and right bundle branches, progressing through
the Purkinje fibers, and finally terminating in individual ventricular cardiomyocytes [source: 30, 31, 32].
T Wave: Exhibits ventricular repolarization, signaling the end of the mechanical systolic phase [source: 33].
BOARD EXAM ALERT: MECHANICAL PHASES OF VENTRICULAR FILLING
Blood  returns  to  the  atria  continuously.  As  blood  accumulates,  atrial  pressure  rises  until  it  exceeds
intraventricular pressure, forcing the AV valves open [source: 38, 39]. Ventricular filling occurs via two distinct
mechanisms:
Passive Filling Phase: Accounts for approximately 75% of total ventricular filling volume [source: 40].
Active Atrial Systole ("Atrial Kick"): Mediated by active atrial contraction, contributing 15% of total
diastolic volume, while slow filling (diastasis) adds approximately 5% [source: 41, 83]. The onset of atrial
systole coincides with the P wave [source: 42].
• 
• 
• 
• 
• 
• 
Anesthesia Board Certification Study Guide - Cardiac Physiology Page 1 of 16

Section 3: Ventricular Structure, Biomechanics & Laplace's Law
The architectural alignment of cardiac muscle fibers provides the structural basis for efficient pumping [source: 55].
The left ventricle (LV) possesses an ellipsoid shape resulting from the laminar layering of spiraling bundles of
cardiac  muscle  [source:  56].  The  fiber  orientation  is  longitudinal  in  the  subepicardial  myocardium,  shifts  to
circumferential in the middle segment, and becomes longitudinal again in the subendocardial myocardium [source:
57]. This configuration allows the LV to eject blood via a highly efficient corkscrew motion starting from the base
and progressing to the apex [source: 60]. This complex architecture maximizes myocyte shortening, increases wall
thickness, and generates powerful systolic force [source: 61]. The subsequent untwisting of the LV provides an
energetic suction mechanism that assists early diastolic filling [source: 62].
In  contrast,  the  right  ventricle  (RV)  pumps  against  the  significantly  lower-pressure  circuit  of  the  pulmonary
circulation [source: 67]. Consequently, the RV free wall thickness is considerably less than that of the LV [source:
68].  The  RV  is  crescent-shaped,  and  its  contraction  mechanics  are  more  complex:  inflow  and  outflow  tract
contractions are non-simultaneous, and a substantial portion of the RV contractile force is recruited from the
interventricular forces generated by the LV-based septum [source: 68, 69, 70].
MATHEMATICAL PRINCIPLE: LAPLACE'S LAW & VENTRICULAR HYPERTROPHY
Myocardial wall stress (σ) is a primary determinant of myocardial oxygen demand and represents the energy
required for contraction [source: 105, 106]. It is mathematically governed by Laplace's Law [source: 107]:
σ = P × R / 2h
Where P is intraventricular pressure, R is ventricular radius, and h is myocardial wall thickness [source: 107].
Pathophysiological Implication (Aortic Stenosis & Hypertension):  In conditions like aortic stenosis or
chronic hypertension, afterload is drastically increased [source: 100]. The ventricle must generate extremely
high pressure (P) to overcome the obstruction and eject blood [source: 110]. To compensate and maintain wall
stress (σ) at normal control levels, the ventricle undergoes concentric left ventricular hypertrophy, increasing
wall thickness ( h) [source: 111, 119]. This increase in h mathematically offsets the elevated P [source: 121].
Conversely, in a failing, dilated heart, the ventricular radius ( R) increases, which directly amplifies wall stress
and dramatically accentuates myocardial oxygen consumption [source: 113, 166].
Section 4: Frank-Starling Mechanism & Contractility
The Frank-Starling relationship is an intrinsic property of the myocardium whereby stretching of the sarcomere
results in enhanced mechanical performance during subsequent contractions [source: 114]. Electron microscopy
indicates that a sarcomere length of 2.0 to 2.2 μm is optimal, as it maximizes the physical cross-bridging between
actin (thin filament) and myosin (thick filament) proteins [source: 123].
While skeletal muscle experiences a sharp decline in force when shortened, cardiac muscle is far more resilient: a
reduction to 80% of optimal sarcomere length results in only a 10% decrease in contractile force [source: 125, 126].
The cellular basis of this unique property is myofilament length-dependent activation—an intrinsic mechanism
where longer sarcomere lengths directly increase the responsiveness and sensitivity of cardiac myofilaments to
activating calcium (Ca²⁺) ions [source: 127]. In clinical practice, this mechanism is demonstrated via the relationship
between left ventricular end-diastolic volume (LVEDV) and stroke volume (SV) [source: 128].
Anesthesia Board Certification Study Guide - Cardiac Physiology Page 2 of 16

Contractility (Inotropic State): Contractility represents the intrinsic level of contractile performance independent of
loading conditions [source: 131, 176]. Each unique level of contractility defines a specific Frank-Starling curve
[source:  131].  Factors  that  shift  the  Frank-Starling  curve  leftward/upward  (enhancing  the  inotropic  state)  or
rightward/downward (depressing contractility) include [source: 132, 141]:
Enhancing Factors: Exercise, adrenergic stimulation, and positive inotropic pharmacologic agents (e.g.,
milrinone, digitalis) [source: 133].
Depressing Factors: Pathological conditions like heart failure or fatal myocardial depression, changes in
temperature, and alterations in pH [source: 133, 140].
In the intact heart, contractility cannot be entirely isolated from loading conditions [source: 177]. It is best evaluated
invasively via pressure-volume (PV) loops [source: 147]. Clinically, the most common noninvasive surrogate index
of contractility is the Ejection Fraction (EF), calculated as [source: 149, 156]:
Ejection Fraction = (LVEDV - LVESV) / LVEDV
Section 5: Cardiac Work, Energetics & Efficiency
Total cardiac energy consumption is divided into external work and internal work, both of which consume oxygen
[source: 157, 161]:
External Work (Stroke Work): The mechanical energy expended to physically eject a volume of blood under
pressure into the vasculature [source: 158]. It is defined as: Stroke Work = SV × P or (LVEDV - LVESV) × P
[source: 160, 161].
Internal Work: The energy expended within the ventricle to alter the geometric shape of the heart and generate
the tension required to prepare for ejection [source: 158]. Wall stress is directly proportional to internal work, and
internal work contributes significantly to overall cardiac inefficiency [source: 159, 160].
CLINICAL APPLICATION: CARDIOPULMONARY BYPASS LINE SAFETY
The clinical significance of internal work is heavily emphasized in the setting of a poorly drained left ventricle
during cardiopulmonary bypass [source: 162]. Even though the bypass roller pump performs all necessary
systemic external work, a failure to fully drain the LV allows blood to accumulate inside the chamber [source:
163]. This stretches the ventricular wall, elevates wall tension, and dramatically increases internal work and
oxygen consumption, which can precipitate severe, hidden myocardial ischemia despite total bypass support
[source: 163].
Cardiac efficiency is evaluated utilizing the following formula [source: 164]:
Cardiac Efficiency = External Work / Energy Equivalent of O₂ Consumption
Ventricular  dilation  in  heart  failure  significantly  impairs  cardiac  efficiency  [source:  166].  The  increased  radius
increases wall stress, which drives up oxygen consumption without any corresponding increase in external stroke
work [source: 166].
• 
• 
• 
• 
Anesthesia Board Certification Study Guide - Cardiac Physiology Page 3 of 16

Section 6: Cellular Anatomy & Excitation-Contraction Coupling (ECC)
At the cellular level, the myocardium consists of contracting cardiomyocytes, conducting tissue, and an extracellular
connective tissue matrix composed predominantly of thick collagen type I fibers cross-linked with thin collagen type
III fibers [source: 187, 189]. Contracting cardiomyocytes occupy approximately 50% of their cellular volume with
rod-like bundles called myofibrils, which contain the core contractile elements [source: 205, 206].
The Cardiac Action Potential: Ion fluxes across plasma membranes are mediated by voltage-gated, ion-selective
channel proteins [source: 253, 254]. Cardiac tissues display two primary categories of action potentials [source:
256]:
Fast-Response Action Potentials: Found in the His-Purkinje system and atrial/ventricular cardiomyocytes
[source: 256]. 
Phase 0 (Rapid Upstroke): Mediated by a massive, rapid influx of sodium (Na⁺) ions through voltage-gated
sodium channels once threshold potential is reached [source: 260, 269].
Phase 1 (Transient Repolarization): Brief, limited repolarization caused by the activation of a transient
outward potassium current (i_{to}) [source: 263].
Phase 2 (Plateau Phase): Characterized by an electrical balance between the inward flux of calcium (Ca²⁺)
ions through L-type calcium channels and the outward efflux of potassium (K⁺) ions through several channels
(inwardly rectifying i_{k1}, delayed rectifier i_k, and i_{to}) [source: 265, 269].
Phase 3 (Final Repolarization): Achieved when potassium efflux through the outward currents heavily
exceeds the declining calcium influx, returning the membrane potential to its resting level [source: 266, 269].
Phase 4 (Resting Membrane Potential): Maintained by the ATP-dependent Na⁺-K⁺-ATPase pump and the
Na⁺-Ca²⁺ exchanger (NCX), which extrudes Ca²⁺ from the cell [source: 270].
Slow-Response Action Potentials: Found in the specialized pacemaker cells of the SA and AV nodes [source:
257]. Pacemaker cells display automaticity due to a regular, spontaneous diastolic depolarization during Phase
4 [source: 274]. This phase is driven by an increase in three inward currents—two mediated by calcium (i_{CaL}
and i_{CaT}) and one mixed cation pacemaker current (I_f, or "funny" current)—accompanied by a concurrent
decrease in two outward potassium currents (i_k and i_{k1}) [source: 276].
Excitation-Contraction Coupling (ECC) & Calcium Dynamics:
Depolarization spreads down the sarcolemma and invaginates deep into the cell through transverse tubules (T-
tubules) [source: 211, 280].
Voltage-gated L-type calcium channels open, allowing a small influx of extracellular Ca²⁺ [source: 285, 296].
This minor influx occurs in close physical proximity to the junctional sarcoplasmic reticulum, where ryanodine
receptors (RyRs) reside [source: 215, 304]. Extracellular calcium binds to the RyRs, triggering a massive,
locally regenerative release of stored calcium from the SR (Calcium-Induced Calcium Release), and its
elementary localized signaling event is a calcium spark [source: 296, 297, 298].
The resulting surge in intracellular free cytosolic calcium (iCa²⁺) allows calcium to bind to Troponin C (TnC),
initiating myofilament contraction [source: 295, 355].
Myocyte Relaxation: To terminate contraction and initiate relaxation, calcium must be actively cleared from the
cytosol via the sarcoplasmic reticulum Ca²⁺-ATPase (SERCA 2A) pump [source: 307, 362]. At rest, the SERCA
pump is tonically inhibited by the dephosphorylated form of the membrane protein phospholamban [source:
308, 309]. Following β-adrenergic stimulation, protein kinases phosphorylate phospholamban, inactivating it and
1. 
◦ 
◦ 
◦ 
◦ 
◦ 
2. 
• 
• 
• 
• 
• 
Anesthesia Board Certification Study Guide - Cardiac Physiology Page 4 of 16

accelerating calcium reuptake into the SR (a positive lusitropic effect) [source: 310, 312, 387]. Inside the SR,
calcium is bound and stored by calsequestrin and calreticulin [source: 313].
PATHOPHYSIOLOGICAL FAILURE MECHANISMS: MYOCARDIAL SIGNALING ERRORS
Heart Failure: Characterized by a pathological increase in spontaneous Ca²⁺ leak from the RyR channels
in the SR [source: 318]. This leak removes vital calcium stores during diastole, significantly reducing
subsequent systolic contractile force and contributing to the profound reduction in contractility (inotropy)
seen in heart failure [source: 319].
Hypertrophy Signatures: Prolonged, abnormal intracellular calcium homeostasis activates calcineurin
and Calcium-calmodulin-dependent protein kinase II (CaMKII) [source: 322, 323]. Calcineurin acts via a
nuclear factor of activated T-cells pathway to alter gene expression and drive pathological myocardial
hypertrophy [source: 322].
The Contractile Apparatus:  The basic working unit of contraction is the sarcomere, defined as the distance
between two structural Z lines [source: 324, 325]. Z lines anchor the thin filaments (actin) and the giant elastic
structural protein  titin [source: 329, 330]. Titin acts as the primary determinant of the passive compliance and
elastic properties of the myocardium at small ventricular volumes [source: 368]. The myosin molecule consists of a
filament body and a bilobar head containing an actin-binding cleft and an ATP-binding pocket housing  myosin
ATPase activity  [source:  340,  342].  Contraction  proceeds  via  cross-bridge  cycling:  calcium  binding  to  TnC
increases the TnC-TnI interaction, which breaks the inhibitory hold of Troponin I (TnI) on the actin filament [source:
355, 356]. This induces conformational shifts in tropomyosin, allowing the myosin head to bind actin [source: 357].
Hydrolysis of ATP by myosin ATPase changes the configuration of the myosin head to deliver the power stroke,
moving the actin and myosin filaments past each other and bringing the Z lines closer together [source: 332, 359].
• 
• 
Anesthesia Board Certification Study Guide - Cardiac Physiology Page 5 of 16

Familial Hypertrophic Cardiomyopathy (Sarcomeric
Disease)
Familial Dilated Cardiomyopathy (FDCM)
(Cytoskeletal Disease)
Definition: An inherited autosomal dominant disease of
the sarcomere proteins. It stands as the most common
cause of sudden cardiac death in otherwise healthy
young individuals [source: 333].
Clinical Features: Marked left ventricular hypertrophy,
severe myocyte and myofibrillar architectural disarray
[source: 334].
Identified Genetic Mutations (8 Sarcomeric Genes)
[source: 335, 336]:
β-cardiac myosin heavy chain
Cardiac troponin T (TnT)
α-tropomyosin
Cardiac myosin-binding protein C
Essential or regulatory myosin light chains
Cardiac troponin I (TnI)
α-cardiac actin
Titin
Definition: An inherited disorder primarily affecting the 
cytoskeleton proteins within the cytoplasm that link,
anchor, and tether internal structural elements [source:
381, 382].
Identified Genetic Basis [source: 383]:
• X-linked FDCM: Mutations in genes encoding 
dystrophin and G4.5.
• Autosomal Dominant FDCM: Mutations in genes
encoding actin, desmin (the intermediate filament
connecting the nucleus to the plasma membrane to
transmit stress/strain), lamin A/C, and δ-sarcoglycan. 
Section 7: Neurohumoral Regulation & Receptor Cascades
Neural Control via the Autonomic Nervous System:  Regulation of cardiac function involves opposing inputs
from the sympathetic and parasympathetic nervous systems [source: 387]. At rest, the heart maintains a high tonic
level  of  parasympathetic  nerve  firing  with  minimal  sympathetic  tone,  making  the  parasympathetic  system  the
dominant resting control mechanism [source: 390, 391]. Exercise or stress shifts this balance toward sympathetic
dominance [source: 392].
Sympathetic Regulation: Neurotransmitter is norepinephrine [source: 387]. It mediates positive chronotropic,
inotropic, and lusitropic responses [source: 387]. Norepinephrine binds to G protein-coupled adrenoceptors
(GPCRs) [source: 406, 407]: 
β₁-Adrenoceptors: The predominant subtype in the human heart (atria and ventricles) [source: 410].
β₂-Adrenoceptors: Account for a substantial proportion in the atria and approximately 20% in the left
ventricle [source: 410]. Their cardiostimulant effect is disproportionately high relative to their density because
β₂-receptors possess tighter structural coupling to the intracellular adenylyl cyclase signaling pathway
[source: 412].
Both β₁ and β₂ receptors couple to the stimulatory G-protein (G_s), activating adenylyl cyclase to synthesize
cyclic adenosine monophosphate (cAMP) [source: 413]. Accumulated cAMP stimulates Protein Kinase A
(PKA), which directly phosphorylates key target proteins: L-type calcium channels, phospholamban, and
Troponin I [source: 413, 414].
α₁-Adrenoceptors (α_{1A}, α_{1B}, α_{1D}): Couple to the G_q protein to activate the phospholipase C-
diacylglycerol-inositol triphosphate (IP₃) system, increasing intracellular calcium and myofilament sensitivity
• 
• 
• 
• 
• 
• 
• 
• 
1. 
◦ 
◦ 
◦ 
◦ 
Anesthesia Board Certification Study Guide - Cardiac Physiology Page 6 of 16

[source: 418, 421]. They mediate a minor positive inotropic response [source: 420]. Pathological cardiac
hypertrophy is primarily driven by chronic α_{1A} receptor activation, signaling through protein kinase C
(PKC) and mitogen-activated protein kinase (MAPK) [source: 422].
α₂-Adrenoceptors (α_{2A}, α_{2B}, α_{2C}): Couple to G_i to inhibit adenylyl cyclase [source: 423]. In the
atrium, prejunctional α₂ receptors (specifically the α_{2C} subtype) provide presynaptic negative feedback,
inhibiting further norepinephrine release from sympathetic nerve terminals [source: 424, 425].
Parasympathetic Regulation: Innervates the heart through the vagus nerve [source: 395]. Supraventricular
pacemaker and conduction tissues receive highly intense vagal innervation, whereas the ventricles receive
sparse innervation [source: 396]. The neurotransmitter is acetylcholine, which binds to muscarinic receptors
[source: 389, 397]. The predominant subtype in the mammalian heart is the M₂ receptor, which couples to the
inhibitory G-protein (G_{i/o}) to directly inhibit adenylyl cyclase [source: 399, 402]. Activation of M₂ receptors
reduces pacemaker automaticity, slows AV node conduction, directly decreases atrial contractile force, and
exerts negative modulatory control over ventricular inotropy [source: 398]. M₃ receptors are expressed in the
coronary circulation [source: 400].
Hormonal Modulators of Cardiac Function:
Angiotensin II: The primary effector hormone of the renin-angiotensin system [source: 445]. It is produced and
secreted by cardiomyocytes and acts via two receptor subtypes: AT₁ and AT₂ [source: 445, 448]. The AT₁
receptor is the dominant subtype in the normal adult heart; its stimulation induces a positive inotropic and
chronotropic effect, promotes fibroblast/myocyte cell proliferation, and stimulates the release of aldosterone and
catecholamines [source: 449, 450, 451]. Chronic, pathological AT₁ activation directly drives adverse myocardial
remodeling, cardiac hypertrophy, and heart failure progression [source: 452]. Conversely, the AT₂ receptor is
highly abundant in the fetal heart, declines rapidly after birth, is upregulated in response to ischemia or injury,
and mediates counterregulatory, antiproliferative effects [source: 453, 454, 455].
Natriuretic Peptides (ANP and BNP): Polypeptides released in direct response to increased myocardial wall
stretch [source: 459]. Atrial natriuretic peptide (ANP) is synthesized and secreted by the atria; B-type natriuretic
peptide (BNP) is produced by the ventricles [source: 459]. Both bind to guanylyl cyclase-coupled natriuretic
peptide receptors to synthesize the second messenger cyclic guanosine monophosphate (cGMP), acting as an
endocrine buffer against hemodynamic pressure or volume overload [source: 460]. In patients with chronic heart
failure, elevated serum ANP and BNP levels serve as powerful, independent predictors of mortality [source:
462].
Adrenomedullin: A peptide hormone synthesized and secreted by cardiomyocytes [source: 462, 444]. It
stimulates adenylyl cyclase, increases cAMP, and possesses direct positive inotropic and chronotropic actions
[source: 463]. It also stimulates endothelial nitric oxide (NO) production, functioning as a potent systemic
vasodilator [source: 464].
Aldosterone: A mineralocorticoid steroid hormone that binds to nuclear mineralocorticoid receptors [source:
465, 467]. It increases the expression and activity of cardiac ionic homeostasis and pH-regulating proteins
(including Na⁺/K⁺-ATPase, the Na⁺-K⁺ cotransporter, the Cl⁻-bicarbonate exchanger, and the Na⁺-H⁺ antiporter)
[source: 467]. Pathologically, aldosterone induces progressive cardiac fibrosis in both ventricles, causing severe
diastolic stiffness and mechanical pump dysfunction [source: 468].
Sex Steroid Hormones: Myocardial contractility is intrinsically more intense in premenopausal women than in
age-matched men; withdrawal of hormone replacement therapy in postmenopausal women triggers a rapid
reduction in contractile performance [source: 476]. Healthy premenopausal women exhibit a lower
cardiovascular risk profile than men due to sex hormone-mediated cardiac modulation [source: 477, 478]. 
Estradiol-17β (E₂) binds to two nuclear estrogen receptor subtypes in the heart: ERα and ERβ [source: 478,
◦ 
2. 
• 
• 
• 
• 
• 
Anesthesia Board Certification Study Guide - Cardiac Physiology Page 7 of 16

479]. E₂ coordinates rapid, non-genomic signaling pathways, including the acute stimulation of vascular
endothelial nitric oxide synthase (eNOS) to synthesize NO and mediate vasodilation, which accounts for the
lower baseline systolic blood pressures in premenopausal women [source: 487, 488, 489]. In men, normal
vascular tone is preserved via the aromatase-mediated local conversion of testosterone to estrogen [source:
490]. Mechanistically, estrogen activation of ERβ confers immediate cardioprotection against acute ischemia/
reperfusion injury in models of myocardial infarction, whereas testosterone exerts the opposite effect [source:
499, 500]. Estrogen's modulatory actions on myocardial calcium channels also underlie key electrophysiologic
sex differences, such as the faster baseline resting heart rate in women and their significantly increased
propensity for drug-induced prolonged QT syndrome [source: 498]. Progesterone and testosterone bind to
nuclear progesterone and androgen receptors in the heart, modifying postsynaptic and presynaptic
sympathoadrenergic functions [source: 480, 481, 482].
Anesthesia Board Certification Study Guide - Cardiac Physiology Page 8 of 16

Section 8: High-Yield Cardiac Reflexes (Board Exam Reference Table)
Cardiac  reflexes  are  fast-acting  reflex  loops  between  the  heart  and  the  central  nervous  system  (CNS)  that
contribute to the immediate regulation of cardiac function and maintenance of physiologic homeostasis [source:
505]. Specific cardiac receptors elicit responses via myelinated or unmyelinated afferent fibers traveling along the
vagus and glossopharyngeal nerves, which are processed in the medulla oblongata before sending sympathetic or
parasympathetic efferents to alter vascular tone, heart rate, and contractility [source: 506, 507, 509, 510].
Anesthesia Board Certification Study Guide - Cardiac Physiology Page 9 of 16

Reflex Name
Anatomic
Receptors &
Afferents
Physiological Triggers Efferent Response & High-Yield
Anesthesia Considerations
Baroreceptor Reflex
(Carotid Sinus Reflex)
Circumferential/
longitudinal stretch
receptors in carotid
sinus & aortic arch
[source: 515].
Afferents:
Glossopharyngeal
(Hering's nerve) &
Vagus nerves to the
nucleus solitarius in
the medulla [source:
516].
Acute changes in
arterial blood pressure
(stretch receptors
heavily activate when
systemic pressure
exceeds 170 mm Hg)
[source: 512, 520].
Operates as a critical
negative feedback loop
[source: 513].
Efferent: Elevated pressure drives
decreased sympathetic activity and
increased parasympathetic tone,
lowering contractility, HR, and
vascular tone [source: 521, 523].
Hypotension drives opposite effects
[source: 524].
Anesthesia Pearls:
Provides vital defense during acute
hemorrhage/shock, but loses all
functional capacity when blood
pressure drops below 50 mm Hg
[source: 531, 532].
Volatile Anesthetics (particularly
halothane) heavily inhibit the
heart rate component of this
reflex [source: 534].
Concomitant use of calcium
channel blockers, ACE inhibitors,
or phosphodiesterase inhibitors
severely blunts the compensatory
vasoconstrictive response by
altering peripheral vasculature or
interfering with central Ca²⁺/
angiotensin signaling [source: 535,
536].
Patients with chronic hypertension
frequently exhibit profound
perioperative circulatory instability
due to a blunted, reset
baroreceptor reflex [source: 536].
Chemoreceptor
Reflex
Chemosensitive
cells located in the
carotid and aortic
bodies [source:
537].
Arterial hypoxemia
(PaO₂ < 50 mm Hg) or
systemic metabolic/
respiratory acidosis
[source: 538, 539].
Efferent: Afferents signal the
medullary chemosensitive area, which
aggressively stimulates respiratory
centers to increase ventilatory drive
[source: 539, 540]. Concurrently, it
increases parasympathetic efferent
outflow to reduce heart rate and
depress myocardial contractility
[source: 541]. Crucially, if hypoxia
remains persistent and uncorrected,
direct CNS stimulation supervenes,
• 
• 
• 
• 
Anesthesia Board Certification Study Guide - Cardiac Physiology Page 10 of 16

Reflex Name
Anatomic
Receptors &
Afferents
Physiological Triggers Efferent Response & High-Yield
Anesthesia Considerations
resulting in a secondary surge in
sympathetic outflow [source: 542].
Bainbridge Reflex Stretch receptors
situated in the right
atrial wall and the
cavoatrial junction
[source: 543].
An increase in right-
sided venous return
and filling pressure
(hypervolemia) [source:
544].
Efferent: Vagal afferent signals travel
to the medullary cardiovascular control
center, where they directly inhibit
parasympathetic efferent tone,
resulting in a compensatory
acceleration of the heart rate to
effectively pump the fluid load forward
[source: 544, 545]. HR acceleration
also results from a direct mechanical
stretch applied to the SA node itself
[source: 546]. The magnitude of the
response is dependent on the
baseline heart rate prior to stimulation
[source: 547].
Bezold-Jarisch
Reflex
Chemoreceptors
and
mechanoreceptors
embedded within
the left ventricular
wall [source: 548].
Noxious ventricular
stimuli (e.g., severe
myocardial ischemia,
acute infarction,
thrombolysis,
revascularization, or
syncope) [source: 548,
551].
Efferent: Signals propagate along
unmyelinated vagal afferent-type C
fibers [source: 549]. Triggers a
profound reflex increase in central
parasympathetic efferent tone [source:
549]. Produces the classic triad of
hypotension, bradycardia, and
coronary artery dilatation [source:
548]. Considered an intrinsic
cardioprotective mechanism to reduce
myocardial oxygen demand [source:
550]. Modulated by endogenous ANP/
BNP via natriuretic peptide receptors;
the reflex is notably less pronounced
or absent in patients with cardiac
hypertrophy or atrial fibrillation
[source: 552, 553].
Valsalva Maneuver Systemic
baroreceptors
responding to
altered thoracic
pressures [source:
556].
Forced expiration
against a strictly closed
glottis [source: 554].
Efferent: Increased intrathoracic and
central venous pressures drastically
reduce venous return, causing an
acute drop in cardiac output and
systemic blood pressure [source: 554,
555]. This drop is sensed by
baroreceptors, reflexively triggering a
massive sympathetic discharge that
increases heart rate and myocardial
contractility [source: 556]. When the
glottis opens, venous return instantly
Anesthesia Board Certification Study Guide - Cardiac Physiology Page 11 of 16

Reflex Name
Anatomic
Receptors &
Afferents
Physiological Triggers Efferent Response & High-Yield
Anesthesia Considerations
surges, provoking a dramatic rise in
blood pressure that stimulates
parasympathetic efferents, resulting in
a temporary post-maneuver reflex
bradycardia [source: 557, 558].
Cushing Reflex Medullary
vasomotor control
center [source:
560].
Severe cerebral
ischemia caused by a
critical elevation in
intracranial pressure
(ICP) [source: 559].
Efferent: Local ischemia at the
medullary vasomotor center drives an
intense, immediate activation of the
sympathetic nervous system [source:
560]. This causes an acute elevation
in heart rate, myocardial contractility,
and extreme systemic arterial
hypertension to overcome the ICP and
restore cerebral perfusion pressure
[source: 561]. This severe
hypertension subsequently triggers
peripheral baroreceptors, leading to a
characteristic reflex bradycardia
[source: 562].
Oculocardiac Reflex Stretch receptors
localized within the
extraocular muscles
[source: 563, 564].
Mechanical pressure
applied directly to the
globe of the eye or
traction exerted on
surrounding structures
(common during
strabismus or
ophthalmic surgery)
[source: 563].
Efferent: Afferents propagate through
the short and long ciliary nerves,
merging with the ophthalmic division
of the trigeminal nerve (Cranial Nerve
V) at the ciliary ganglion, progressing
to the Gasserian ganglion [source:
564, 565, 566]. This triggers an
intense surge in central efferent
parasympathetic (vagal) tone,
culminating in profound bradycardia or
sinus arrest [source: 566]. Clinical
incidence ranges from 30% to 90%
[source: 567]. Management dictates
immediate cessation of surgical
traction and the administration of
an antimuscarinic drug such as
glycopyrrolate or atropine to block
the vagal efferent loop [source:
568].
Anesthesia Board Certification Study Guide - Cardiac Physiology Page 12 of 16

Section 9: Board-Style Examination Questions
Question 1: A 72-year-old female with severe aortic stenosis is undergoing a choice for anesthetic
titration. Based on Laplace's Law and the data presented in the text, what is the primary biomechanical
mechanism by which concentric left ventricular hypertrophy maintains normal wall stress in this
patient? [source: 107, 110-112]
A. By decreasing the cross-sectional radius of the ventricular chamber to reduce preload.
B. By increasing the myocardial wall thickness (h) to mathematically offset the elevated intraventricular
pressure (P).
C. By accelerating the peak instantaneous rate of pressure decline to improve diastolic suction.
D. By shifting fiber alignment from a circumferential to a purely longitudinal orientation.
Correct Answer: B
Rationale: Laplace's Law states that wall stress (σ) equals the product of pressure (P) and radius (R) divided by
twice the wall thickness (2h): σ = P × R / 2h [source: 107]. In aortic stenosis, the ventricle must generate a
massive intraventricular pressure (P) to overcome the increased afterload [source: 110]. To prevent wall stress
from rising, the ventricle increases its wall thickness (h) via compensatory hypertrophy [source: 111, 119]. This
mathematical increase in the denominator offsets the increase in the numerator (P), maintaining wall stress at
control levels [source: 121]. 
Question 2: During a fast-response myocardial action potential, which specific combination of ion
channel currents governs the extended electrical balance that characterizes the plateau phase (Phase
2)? [source: 265, 269]
A. Rapid inward sodium flux balanced against a transient outward potassium current (i_{to}).
B. Net influx of calcium through L-type calcium channels balanced against the efflux of potassium through the
inwardly rectifying i_{k1}, delayed rectifier i_k, and i_{to} channels.
C. Electrogenic extrusion of calcium via the Na⁺-Ca²⁺ exchanger balanced by the Na⁺-K⁺-ATPase pump.
D. Inward calcium flux through T-type calcium channels balanced by a mixed cation current (I_f).
Correct Answer: B
Rationale: According to the text, the plateau phase (Phase 2) of a fast-response action potential in a ventricular
myocyte occurs due to a precise net balance between the inward influx of calcium (Ca²⁺) through L-type calcium
channels and the outward efflux of potassium (K⁺) through three distinct potassium currents: the inwardly
rectifying i_{k1}, the delayed rectifier i_k, and the transient outward current i_{to} [source: 265, 269]. 
Anesthesia Board Certification Study Guide - Cardiac Physiology Page 13 of 16

Question 3: A patient with chronic congestive heart failure is noted to have a depressed inotropic
state. At the cellular level, what pathological change in calcium handling directly contributes to the
reduction of contractile force and blunted inotropy in heart failure? [source: 318, 319]
A. An excessive accumulation of calsequestrin in the junctional sarcoplasmic reticulum.
B. An abnormal increase in baseline calcium leak from the sarcoplasmic reticulum.
C. Hyper-phosphorylation of phospholamban leading to excessive SERCA 2A pumping activity.
D. Spontaneous up-regulation of the prejunctional alpha-2C adrenoceptor.
Correct Answer: B
Rationale: The text explicitly states that in the failing heart, there is a pathological increase in calcium leak from
the sarcoplasmic reticulum (SR) [source: 318]. This spontaneous leak reduces total stored intra-SR calcium
available for subsequent contractions, significantly reducing contractile force and contributing directly to the
depressed inotropic state (reduced contractility) characteristic of heart failure [source: 319]. 
Question 4: E.H. Starling in 1914 observed the classic relationship between myocardial fiber length and
energy release. In clinical anesthesia practice, what parameters serve as the direct common
surrogates to represent this force-length relationship? [source: 116, 128]
A. Systemic vascular resistance and arterial partial pressure of oxygen.
B. Left ventricular end-diastolic volume (LVEDV) and stroke volume (SV).
C. Transmembrane action potential amplitude and Phase 4 slope.
D. Aortic closing-mitral opening interval and the peak rate of wall thinning.
Correct Answer: B
Rationale: The text points out that a common clinical application of Starling's law is the relationship between left
ventricular end-diastolic volume (LVEDV) and stroke volume (SV), where an increase in end-diastolic volume
(myocardial stretch) translates directly into an increased generation of stroke volume [source: 128, 138, 139]. 
Question 5: Which high-yield cardiac reflex utilizes unmyelinated vagal afferent-type C fibers to
communicate noxious left ventricular stimuli to the medulla, producing a classic cardioprotective triad
of hypotension, bradycardia, and coronary artery dilatation? [source: 548, 549, 550]
A. Bainbridge Reflex
B. Cushing Reflex
C. Oculocardiac Reflex
D. Bezold-Jarisch Reflex
Correct Answer: D
Rationale: The Bezold-Jarisch reflex is triggered by noxious ventricular stimuli (e.g., ischemia or infarction)
sensed by left ventricular wall receptors [source: 548, 551]. These signals propagate along unmyelinated vagal
afferent C fibers to reflexively drive a massive surge in parasympathetic tone, producing the diagnostic triad of
bradycardia, hypotension, and coronary artery dilatation [source: 548, 549]. 
Anesthesia Board Certification Study Guide - Cardiac Physiology Page 14 of 16

Question 6: During an ophthalmic case, traction on the extraocular muscles causes the patient's heart
rate to precipitously drop from 75 bpm to 32 bpm. Which of the following precisely maps the afferent
neural pathway of this reflex loop? [source: 564, 565, 566]
A. Glossopharyngeal nerve to the nucleus solitarius.
B. Short and long ciliary nerves, merging with the ophthalmic division of the trigeminal nerve at the ciliary
ganglion, progressing to the Gasserian ganglion.
C. Unmyelinated vagal C fibers traveling directly to the caudally located depressor center of the medulla.
D. Hering's sinus nerve projecting to the respiratory control center.
Correct Answer: B
Rationale: The text delineates the precise afferent pathway of the oculocardiac reflex: stretch receptors in
extraocular muscles transmit signals via the short and long ciliary nerves [source: 564]. These ciliary nerves
merge with the ophthalmic division of the trigeminal nerve (Cranial Nerve V) at the ciliary ganglion, and the
trigeminal nerve carries these impulses to the Gasserian ganglion, resulting in increased parasympathetic vagal
efferent tone [source: 565, 566]. 
Question 7: The Fick Principle represents a fundamental method for calculating cardiac output based
on the conservation of mass. According to the formula described in the chapter, which variable
represents the denominator when determining total blood flow (Q)? [source: 179, 183]
A. Total pulmonary arterial blood flow multiplied by oxygen concentration.
B. The difference between the pulmonary venous oxygen concentration and pulmonary arterial oxygen
concentration (CpvO₂ - CpaO₂).
C. Total alveolar oxygen consumption divided by systemic vascular resistance.
D. The ratio of stroke volume to the left ventricular end-diastolic pressure.
Correct Answer: B
Rationale: The Fick principle equation yields: Q = q₂ / (CpvO₂ - CpaO₂), where q₂ is total oxygen consumption
and the denominator is the difference between pulmonary venous (peripheral arterial) and pulmonary arterial
(mixed venous) oxygen concentrations [source: 183]. 
Anesthesia Board Certification Study Guide - Cardiac Physiology Page 15 of 16

Question 8: In isolated cardiac muscle preparations, an incremental increase in the frequency of
stimulation induces a corresponding increase in the force of contraction (Treppe / staircase
phenomenon). At what frequency is maximal contractile force reached at a fixed muscle length?
[source: 167, 168]
A. Between 60 and 80 stimuli per minute.
B. Between 100 and 120 stimuli per minute.
C. Between 150 and 180 stimuli per minute.
D. Over 300 stimuli per minute.
Correct Answer: C
Rationale: The text notes that under the force-frequency relationship (Treppe), maximal contractile force is
reached in an isolated heart muscle at a fixed muscle length between 150 and 180 stimuli per minute;
frequencies beyond this extreme result in a decrease in contractile force [source: 168, 170]. 
Question 9: Active reuptake of calcium by the SERCA 2A pump terminates myocardial contraction and
drives lusitropy. At rest, how is the activity of the SERCA 2A pump tonically regulated within the
sarcoplasmic reticulum membrane? [source: 307, 308, 309]
A. It is continuously up-regulated by calreticulin sensors.
B. It is tonically inhibited by the dephosphorylated form of phospholamban.
C. It is down-regulated by high-affinity binding to calmodulin.
D. It is activated via prejunctional alpha-1A adrenoceptor cleavage.
Correct Answer: B
Rationale: The text states that the SERCA pump makes up close to 90% of all SR proteins and is tonically
inhibited by the phosphoprotein phospholamban at rest when it is in its dephosphorylated form [source: 308,
309]. Phosphorylation removes this inhibition, stimulating SERCA 2A and enhancing active relaxation [source:
310, 312]. 
Question 10: Which autonomic receptor subtype is the predominant muscarinic isoform found in the
mammalian heart, and what intracellular signaling cascade does it couple with to exert negative
inotropic and chronotropic control? [source: 399, 402]
A. M₁ receptor, which couples to Gs to stimulate adenylyl cyclase.
B. M₂ receptor, which couples to G_{i/o} to inhibit adenylyl cyclase.
C. M₃ receptor, which couples to Gq/11 to activate phospholipase C.
D. M₅ receptor, which couples to pertussis-insensitive tyrosine kinases.
Correct Answer: B
Rationale: The textbook details that M₂ receptors are the predominant muscarinic subtype found in the
mammalian heart [source: 399]. They couple to the pertussis toxin-sensitive G protein (G_{i/o}) to directly inhibit
adenylyl cyclase, slowing conduction, pacing frequency, and contractility [source: 398, 402]. 
Anesthesia Board Certification Study Guide - Cardiac Physiology Page 16 of 16`
    }
  ]
};
