export const ch42 = {
  id: "miller_ch42",
  chapterNumber: 42,
  title: "Peripheral Nerve Blocks and Ultrasound Guidance for Regional Anesthesia",
  bookId: "miller",
  readTimeMinutes: 23,
  sections: [
    {
      title: `Section 1`,
      content: `STUDY GUIDE & BOARD REVIEW:`
    },
    {
      title: `PERIPHERAL NERVE BLOCKS`,
      content: `Comprehensive Chapter Summary and Question Bank Prep for Regional Anesthesia &
Ultrasound Guidance`
    },
    {
      title: `CORE REVIEW HIGHLIGHTS`,
      content: `Regional anesthesia relies entirely on the precise deposition of local anesthetic adjacent to the target
neural structures.
No  definitive  human  clinical  data  demonstrates  that  any  single  localization  technique  (paresthesia
seeking, nerve stimulation, or ultrasound guidance) reduces the absolute incidence of peripheral nerve
injury over another.
Peripheral  nerves  exhibit  a  characteristic  honeycomb  appearance  under  high-frequency  ultrasound,
generated by an internal matrix of hypoechoic fascicles surrounded by hyperechoic connective tissue
borders.
Ultrasound  provides  dynamic,  real-time  visualization  of  needle  tip  advancement,  adjacent  vascular
anatomy, and the exact distribution pattern of local anesthetic adjustive fluid.
Section 1: Localization Tech & Electrophysiological Principles
Historically, regional anesthetic blocks relied heavily on tactile feedback, anatomical landmarks, and the elicitation
of paresthesias. Modern regional anesthesia combines electrophysiological mapping and real-time visualization to
maximize consistency, block quality, and safety margins.
Peripheral Nerve Stimulation (PNS) Mechanics
Peripheral nerve stimulators emit short pulses of electrical current to the uninsulated tip of a specialized block
needle.  When  the  needle  tip  approaches  a  mixed  or  motor  nerve,  the  electrical  current  induces  neural
depolarization, resulting in visual synchronous muscle contractions. Key electrophysiological parameters include:
Polarity Configurations: The negative terminal (cathode) must always be connected to the stimulating needle,
while  the  positive  terminal  (anode)  is  attached  to  the  patient's  skin  surface.  Cathodal  stimulation  is
approximately  twice  as  efficient as  anodal  stimulation  at  inducing  neural  depolarization.  Skin  electrode
placement does not alter these stimulation properties.
Current Threshold Settings:  Initial needle localization typically begins with a higher current output (>1.5 mA)
to  facilitate  penetration  through  thick  tissue  or  fascial  boundaries.  Once  the  targeted  motor  response  is
accurately identified, the current output is systematically down-regulated to ≤0.5 mA.
The 0.5 mA Threshold:  An evoked motor response obtained at a current of approximately 0.5 mA confirms an
ideal needle-to-nerve relationship for local anesthetic deposition or catheter placement.
Subepineural Warning Threshold:  If a motor response persists at a current output of ≤0.2 mA, the needle tip
may be abutting the epineurium or positioned subepineurally/intraneurally. Injection at this point carries an
unacceptably high risk of structural fascicular injury and must be avoided.
• 
• 
• 
• 
• 
• 
• 
• 
Anesthesia Board Prep Series • Section 42: Regional Anesthesia Page 1

The Raj Test (Impedance & Dissipation):  Following the injection of a small volume of conductive solution
(such as saline or local anesthetic), the current density at the uninsulated needle tip rapidly dissipates, causing
the immediate elimination of the evoked motor response. This confirms proper current conductance.
Pulse Duration Modifications:  Short-duration impulses (0.1 ms) are highly effective at isolating motor nerve
fibers. For pure sensory nerves lacking motor vectors, extending the pulse duration to 0.3 ms will effectively
stimulate sensory fibers, eliciting a reproducible sensory response.`
    },
    {
      title: `2. Fundamentals of Ultrasound Physics & Artifact Manifestations`,
      content: `Ultrasound operates utilizing acoustic sound waves with frequencies vastly exceeding the normal human audible
threshold (>20,000 cycles per second). For high-fidelity diagnostic imaging of superficial peripheral nerves, high-
frequency transducers exceeding 10 MHz are structurally required to achieve optimal axial and lateral resolution.
Ultrahigh frequency sound waves (UHF, >20 MHz) can successfully resolve up to 50% to 60% of the total internal
fascicular content of a target nerve.
Core Modeling Assumptions
The  processing  architecture  of  modern  ultrasound  machines  relies  on  specific  physical  constants  that,  when
violated by local tissue heterogeneities, give rise to predictable diagnostic artifacts:
Acoustic Velocity Homogeneity:  Sound waves are assumed to travel through all human soft tissues at a
constant velocity of  1540 m/s . This uniform constant allows linear interconversion of echo arrival times into
structural distance measurements. Variations between fat and lean tissue cause the Bayonet Artifact, resulting
in an apparent bending of a linear block needle.
Linear Propagation Paths:  Ultrasound waves are assumed to travel along a completely straight path to and
from the transducer face. When sound waves encounter parallel reflective borders, they bounce repeatedly
before returning, generating  Reverberation Artifacts displayed deep to the actual reflector. This is common
along shallow-angled needle shafts.
Central Ray Alignment: All returning reflections are assumed to originate exclusively from the central ray of the
transducer beam profile. If reflectors lie slightly outside this plane, Out-of-Plane (Slice Thickness) Artifacts
occur. Resolving these ambiguities requires multi-planar scanning views.
Fluid-Tissue Interface Phenomena
Posterior Acoustic Enhancement: Unlike adjacent cellular tissues, biologic fluids do not significantly attenuate
the passing ultrasound beam. This preserves high energy down the beam path, creating a region of structural
hyperechoicity deep to fluid structures (e.g., blood vessels, cysts). This enhancement can easily be misidentified
as a peripheral nerve structure.
Acoustic Shadowing: Occurs when the sound beam encounters an extremely strong reflecting interface (such
as  the  cortical  surface  of  mature  bone  or  dense  calcification).  Virtually  all  energy  is  reflected,  leaving  a
completely dark, echo-free void deep to the structure.
Anisotropy: A  physical  phenomenon  wherein  the  amplitude  of  received  reflections  varies  dramatically
depending on the angle of beam insonation. Nerves and tendons appear bright and well-defined when the beam
hits them at a strict 90-degree angle, but fade into hypoechoic obscurity if the probe is tilted slightly. Tendons
display significantly more pronounced anisotropy than nerves.
• 
• 
1. 
2. 
3. 
• 
• 
• 
Anesthesia Board Prep Series • Section 42: Regional Anesthesia Page 2`
    },
    {
      title: `3. Transducer Manipulation Nomenclature & Doppler Principles`,
      content: `Achieving a high-fidelity image requires systematic probe adjustments. Standardized nomenclature outlines five
distinct transducer movements:
Transducer
Movement Mechanical Description Primary Clinical Objective
Sliding
Moving the transducer face linearly along the
skin surface along the known vector path of a
nerve.
Tracking small nerves in short-axis across an
extended course (e.g., "ski lift" or "elevator"
technique).
Tilting Angling the transducer face side-to-side
across the cross-plane Axis.
Optimizing the angle of insonation to combat
anisotropy and maximize nerve brightness.
Compression Applying downward vertical pressure with the
transducer face against the patient's skin.
Coapting thin-walled venous structures to
differentiate them from arteries and bringing
deep targets closer.
Rocking
Tipping the probe face inline with the long
axis (toward or away from the structural
indicator).
Improving needle visualization and beam
alignment when working room is restricted by
bone.
Rotation Turning the transducer axis horizontally to
adjust the scan plane orientation.
Transitioning smoothly between true short-axis,
oblique, and long-axis structural views.
Doppler Flow Imaging Modes
Doppler imaging utilizes frequency shifts generated when sound waves reflect off moving red blood cells to map
vascular networks and prevent accidental intravascular injection:
Traditional Color Doppler:  Processes and encodes the mean frequency shifts. It provides directional and
velocity data relative to the probe face, color-coded such that flow away from the transducer is blue, and flow
toward the transducer is red. Flow running exactly perpendicular (90 degrees) to the beam drops out completely
due to the cosine of 90 degrees being zero.
Power Doppler: Processes the integration of the total power spectrum rather than frequency velocity shifts.
While Power Doppler completely sacrifices directional velocity data, it offers significantly greater sensitivity for
low-flow vessels and is almost completely independent of the angle of insonation.`
    },
    {
      title: `4. Upper Extremity Blocks (Brachial Plexus Pathways)`,
      content: `The brachial plexus is derived from the anterior primary rami of C5-T1. Understanding its longitudinal breakdown
(Roots → Trunks → Divisions → Cords → Branches) is paramount for safe needle approaches.
Interscalene Brachial Plexus Block (ISB)
Indications: Major surgical procedures involving the shoulder and proximal humerus. It is strictly avoided/not
recommended for forearm or hand surgery due to high rates of  inferior trunk (C8-T1) sparing  (ulnar nerve
distribution).
• 
• 
• 
Anesthesia Board Prep Series • Section 42: Regional Anesthesia Page 3

Sonoanatomy & Alignment: High-frequency linear probe placed transversely across the neck at the C6 level.
The trunks are visualized as an aligned row of hypoechoic nodules positioned between the anterior scalene
(AS) and middle scalene (MS) muscles, forming the classic "stoplight sign."
Technique Details: Needle advanced out-of-plane or in-plane from lateral to medial. The out-of-plane approach
facilitates catheter threading and minimizes the risk of direct needle trauma to the long thoracic and dorsal
scapular nerves embedded within the middle scalene belly. Targeted volume: 10-15 mL.
Critical Complications:  Ipsilateral phrenic nerve block and resultant hemidiaphragmatic paresis are nearly
inevitable when utilizing traditional large-volume (>15 mL) techniques at the C6 level. This can precipitate acute
respiratory  decompensation  in  patients  with  severe  preexisting  pulmonary  compromise  or  contralateral
diaphragmatic paralysis. Other side effects include vagus/recurrent laryngeal nerve block (hoarseness), cervical
sympathetic  chain  block  (Horner  Syndrome),  and  the  Bezold-Jarisch  reflex (profound  bradycardia,
hypotension, syncope) triggered by decreased venous return in awake, sitting shoulder surgery patients.
Superior Trunk & Anterior Suprascapular Nerve Blocks
Developed as phrenic-sparing alternatives to the traditional ISB for shoulder surgery. The suprascapular nerve
provides roughly 70% of the sensory supply to the shoulder joint. By sliding the probe distally from the interscalene
space,  the  suprascapular  nerve  can  be  dynamically  visualized  branching  off  the  superior  trunk  deep  to  the
omohyoid muscle within the posterior cervical triangle. Depositing 5-15 mL of local anesthetic shallow to the
prevertebral fascia targets the joint fibers while preventing cephalad track along the phrenic pathway. Color Doppler
is mandatory to differentiate the nerve from the adjacent transverse cervical and suprascapular arteries.
Supraclavicular Brachial Plexus Block
Targets the brachial plexus at the distal trunk/proximal division level where the architecture is highly compact,
leading to rapid, high-density anesthesia of the entire upper extremity distal to the shoulder (elbow, forearm, hand).
The trunks/divisions are visualized vertically clustered lateral to the pulsatile subclavian artery directly overlying the
hyperechoic first rib. The needle approaches in-plane from lateral to medial, using the wide first rib as a structural
shield to protect the underlying pleural dome. Targeted volume: 15-30 mL; excessive volumes risk local neural
ischemic compression. Phrenic nerve block incidence remains high (40-60%).
Infraclavicular Brachial Plexus Block
Provides complete anesthesia of the distal arm while offering an exceptionally stable anatomical environment for
continuous catheters without requiring arm manipulation. Injection targets the lateral, medial, and posterior cords
clustered around the second part of the axillary artery deep to the pectoralis major and minor muscles.
Table 42.1: Sonographic Landmarks for Infraclavicular Block
Proximal Boundaries Optimal Injection Location Distal Boundaries
Cephalic vein Pectoralis minor muscle (midportion) Subscapular artery
Thoracoacromial artery Brachial plexus cords surrounding axillary artery Coracobrachialis muscle
Chest wall and pleura Posterior (or medial) cord underneath axillary artery Anterior & Posterior circumflex arteries
Sonographic Signs of Infraclavicular Success (Box 42.2):  A typical "U-shaped" distribution of local anesthetic
underneath the axillary artery, separation of all three cords from the artery, a "white wall" appearance of the free
walls of the artery, and reduction in axillary artery diameter during injection.
• 
• 
• 
Anesthesia Board Prep Series • Section 42: Regional Anesthesia Page 4

Axillary Brachial Plexus Block
Highly effective for surgical procedures of the distal upper arm, elbow, and hand. Under ultrasound guidance,
practitioners target the individual terminal nerves (median, ulnar, radial) surrounding the third part of the axillary
artery at the level of the conjoint tendon of the latissimus dorsi and teres major. The musculocutaneous nerve must
be targeted separately as it leaves the plexus sheath proximally to travel within the belly of the coracobrachialis
muscle.  To  completely  cover  tourniquet  pain,  dedicated  blocks  of  the  medial  brachial  cutaneous  and
intercostobrachial nerves must be performed superficial to the brachial fascia.
Table 42.2: Comparison of Infraclavicular and Axillary Approaches
Parameter Matrix Infraclavicular Block Approach Axillary Block Approach
Anatomical Depth Deep (traverses two overlying muscle
layers) Shallow / Superficial field
Block Onset Speed Slower systemic latency Rapid clinical onset
Tourniquet Tolerance Excellent procedural coverage Fair (requires additional auxiliary
branches)
Catheter Management
Success High stability (robust tissue anchoring) Low stability (high dislodgement rates)`
    },
    {
      title: `5. Advanced Truncal Block Formulations`,
      content: `Truncal blocks provide targeted, unilateral somatic and visceral analgesia for chest wall and abdominal procedures,
successfully avoiding the bilateral motor block and cardiovascular alterations typical of central neuraxial blocks.
Paravertebral Block
Anatomical Boundaries:  The wedge-shaped thoracic paravertebral space is bounded anterolaterally by the
parietal  pleura,  medially  by  the  vertebral  body/intervertebral  disk/neural  foramen,  laterally  by  the  posterior
intercostal membrane, and posteriorly by the superior costotransverse ligament. It communicates directly with
the epidural space.
Technique Details: A vertically oriented parasagittal needle trajectory is preferred over a transverse approach
due  to  optimized  needle-tip  control  and  superior  multi-segmental  local  anesthetic  spread.  The  needle
approaches in-plane from caudal to cranial, advancing until it pierces the superior costotransverse ligament.
Proper deposition within the paravertebral space is explicitly confirmed by the "smile sign," wherein the local
anesthetic fluid bolus visibly depresses the parietal pleura anteriorly.
Complications: Pneumothorax remains the most clinically significant risk. Medially misdirected needles carry
an elevated risk of accidental dural puncture, high spinal block, or direct intraforaminal spinal cord injury.
Erector Spinae Plane (ESP) Block
A highly popular somatic and visceral analgesic alternative to the paravertebral block for breast and thoracic
surgery  (including  rib  fracture  management).  The  needle  targets  the  structural  periosteum  of  the  transverse
process, depositing local anesthetic directly deep to the erector spinae muscle group. This creates a safe, remote
barrier from the lung, drastically lowering the risk of accidental pneumothorax. Large volumes (15-30 mL) are
utilized, necessitating close vigilance for local anesthetic systemic toxicity (LAST) due to the high vascularity of the
paraspinous musculature.
• 
• 
• 
Anesthesia Board Prep Series • Section 42: Regional Anesthesia Page 5

Transversus Abdominis Plane (TAP) Block
Targets the thoracoabdominal nerves (T6-T12) providing pure somatic analgesia to the lower abdominal wall wall.
Utilizing a midaxillary line approach, the three distinct muscle layers of the abdominal wall are isolated to display the
classic "three-layer-cake appearance" (external oblique, internal oblique, and transversus abdominis). The local
anesthetic is deposited directly into the fascial plane separating the internal oblique and transversus abdominis
muscles. Successful hydrodissection separates the fascial borders to create the pathognomonic  "kayak sign."
Volume: 15-20 mL of dilute local anesthetic. This is a somatic block and does not provide visceral analgesia.`
    },
    {
      title: `6. Lower Extremity Block Techniques`,
      content: `Innervation of the lower extremity is shared between the lumbar plexus (L1-L4) and the sacral plexus (L4-S3).
Precise block placement maximizes motor-sparing outcomes.
Femoral Nerve & Fascia Iliaca Blocks
The femoral nerve sits lateral to the femoral artery within the structural groove formed by the iliacus and psoas
muscles. If the profunda femoris artery is visualized, the transducer is positioned too far distally for a successful
proximal femoral block. For major hip surgeries or preoperative hip fracture pain management, the Suprainguinal
Fascia Iliaca Block  is preferred. A linear probe is aligned perpendicular to the inguinal ligament to visualize the
sartorius and internal oblique muscles. Utilizing hydrodissection, 30-40 mL of dilute local anesthetic is tracked
cephalad beneath the fascia iliaca over the iliacus muscle, reliably blocking the femoral, lateral femoral cutaneous,
and obturator nerves through a single injection site. Both approaches prompt quadriceps weakness, requiring strict
fall-prevention protocols.
Adductor Canal Block
A premier motor-sparing technique for total knee arthroplasty analgesia. The saphenous nerve (a terminal sensory
branch of the femoral nerve) and the nerve to the vastus medialis provide major sensory innervation to the knee
joint. The optimal mid-thigh injection site is isolated by identifying the precise point where the medial border of the
sartorius muscle converges with the medial border of the adductor longus muscle. At this exact locus, a clear
double contour on the roof of the canal identifies the  vastoadductor membrane. Depositing 10-15 mL of local
anesthetic lateral to the femoral artery deep to the sartorius muscle captures the saphenous nerve and the nerve to
the  vastus  medialis  while  completely  sparing  the  quadriceps  motor  function.  Higher  volumes  (>15  mL)  risk
retrograde track, precipitating quadriceps paresis.
Sciatic Nerve & Popliteal Pathways
The sciatic nerve divides into the tibial nerve and common peroneal nerve at or above the popliteal fossa. For foot
and ankle surgeries, the popliteal sciatic block is commonly performed in the supine position with the leg elevated.
The tibial nerve tracks along a straight path posterior to the popliteal vessels and exhibits twice the cross-sectional
area of the common peroneal nerve. The needle tip is positioned cleanly between the two components just
proximal to the bifurcation to guarantee circumferential distribution. The  IPACK Block (Infiltration between the
Popliteal Artery and Capsule of the Knee) serves as an excellent motor-sparing alternative, isolating the posterior
articular branch to handle posterior knee pain without causing foot drop.
Anesthesia Board Prep Series • Section 42: Regional Anesthesia Page 6

Ankle Block Technique
An ankle block provides complete anesthesia of the foot via five separate nerve injections, requiring an intimate
knowledge of deep and superficial tracking layers:
Tibial Nerve: A deep terminal branch. Isolated by identifying the posterior tibial artery at the level of the medial
malleolus; requires a deep injection of 7-10 mL adjacent to the vessel.
Deep Peroneal Nerve: A deep terminal branch. Sits directly deep to the extensor retinaculum, running lateral to
the anterior tibial artery (dorsalis pedis) pulsation between the extensor hallucis longus and extensor digitorum
longus tendons. Requires deep deposition.
Sural Nerve: A superficial sensory branch. Tracks superficially between the lateral malleolus and the Achilles
tendon,  traveling  in  close  proximity  with  the  lesser  saphenous  vein.  Blocked  via  5-10  mL  subcutaneous
infiltration.
Superficial Peroneal Nerve: Blocked via a superficial subcutaneous band of local anesthetic (3-5 mL) directed
laterally from the intermalleolar line across the dorsum of the foot.
Saphenous Nerve:  The sole terminal branch of the femoral nerve at the ankle. Blocked via a superficial
subcutaneous band of local anesthetic (3-5 mL) directed medially from the intermalleolar line around the medial
malleolus.`
    },
    {
      title: `7. Medical Optimization: LAST Management & Universal Contraindications`,
      content: `Universal Contraindications Matrix
Absolute  Contraindications: Patient  outright  refusal;  active  infection  directly  at  the  needle  insertion  site;
documented severe allergy to local anesthetic agents; or a clinical scenario where the block negatively impacts
mandatory postoperative neurological tracking or the surgical approach.
Relative Contraindications: An uncooperative or combative patient; preexisting severe peripheral neuropathy;
or  active  therapeutic  anticoagulation/coagulopathy.  Deep,  non-compressible  blocks  (e.g.,  lumbar  plexus,
posterior paravertebral) or blocks near critical structures (e.g., interscalene hematoma compressing the airway)
become absolute contraindications in the setting of coagulopathy.
Local Anesthetic Systemic Toxicity (LAST) Rescue Protocol
Ultrasound guidance reduces but does not eliminate  the risk of LAST. Toxicity can manifest immediately due to
inadvertent direct intravascular injection, or it may present with delayed onset (up to 30 minutes or more) due to
systemic vascular absorption. Frequent incremental aspiration (every 3-5 mL) and continuous real-time imaging of
fluid spread are mandatory safety barriers. If suspected, immediately execute the following resuscitation plan:
1. 
2. 
3. 
4. 
5. 
• 
• 
Anesthesia Board Prep Series • Section 42: Regional Anesthesia Page 7

Step 1:  Stop local anesthetic administration immediately and call for the LAST rescue cart containing Intralipid.
Step 2:  Establish definitive airway management, ventilating with 100% oxygen. Rapidly correct any acidosis,
hypercarbia, or hypoxemia, as an acidic environment drastically amplifies local anesthetic cardiovascular toxicity.
Step 3:  Halt any ongoing seizure activity using intravenous benzodiazepines (e.g., midazolam). If benzodiazepines
are unavailable, small titrated doses of propofol are acceptable, but propofol must be completely avoided if the
patient exhibits any signs of cardiovascular instability.
Step 4:  Adjust standard ACLS protocols: Omit all local anesthetics (e.g., lidocaine) for arrhythmia management;
utilize Amiodarone as the first-line antiarrhythmic for ventricular ectopy; restrict individual epinephrine boluses to 
≤1 mcg/kg; and completely avoid vasopressin.
Step 5:  Initiate Intravenous Lipid Emulsion (20% Intralipid) Rescue Therapy at the first sign of a serious LAST
event: Administer an initial bolus of 1.5 mL/kg, followed by a continuous infusion of 0.25 mL/kg/min. The absolute
upper safety limit for total lipid dosing is 12 mL/kg.`
    },
    {
      title: `8. Specialized Education: The Six-Step Learning Model`,
      content: `Standardizing training protocols ensures the safe transition of regional anesthesia trainees from simulated models
to direct patient care:
Step 1: Gross Anatomy Mastery  Trainees undergo systematic repetition of regional anatomy to translate basic
textbook structural drawings into real-time sono-anatomy roadmaps, prioritizing the identification of baseline danger
zones.
Step 2: Technology & Preset Optimization  Learning the universal properties of ultrasound equipment, optimizing
machine presets, and manipulating time-gain compensation (TGC) to isolate low-contrast structures.
Step 3: Live Volunteer Workshops  Performing non-invasive scanning on human volunteers to acquire natural
probe manipulation skills (sliding, tilting, compression) and experience normal interindividual anatomical variations.
Step 4: Phantom Simulation Training  Utilizing tissue-equivalent phantoms to practice precise needle-to-probe
alignment, developing identical synchronization between the operator's hands, eyes, and the ultrasound screen to
prevent needle advancement without constant visualization.
Step 5: Human Cadaver Dissection  Participating in specialized embalmed cadaver workshops to integrate
realistic structural resistance and authentic mechanical navigation challenges.
Step 6: Clinical Application under Tutelage  Executing regional blocks on active patients under the strict, real-
time guidance of an experienced tutor, heavily supplemented by modern virtual reality and eye-tracking technology
registries.
Anesthesia Board Prep Series • Section 42: Regional Anesthesia Page 8

BOARD-STYLE EXAMINATION QUESTION`
    },
    {
      title: `BANK`,
      content: `High-Yield Practice Questions for Standardized Exam Preparation
Question 1: You are utilizing a peripheral nerve stimulator (PNS) to facilitate an interscalene
brachial plexus block in an awake patient. Which of the following electrical parameters and
polarity configurations represents the most efficient and appropriate set up?
A. Connect the positive terminal (anode) to the stimulating needle; utilize an initial current output of 0.1 mA.
B. Connect the negative terminal (cathode) to the stimulating needle; down-regulate the current to
a threshold of 0.5 mA once the motor response is isolated.
C.  Connect  the  negative  terminal  (cathode)  to  the  stimulating  needle;  proceed  with  injection  if  motor
twitching persists at 0.15 mA.
D. Connect the positive terminal (anode) to the patient's skin surface; extend pulse duration to 0.3 ms to
selectively map the motor fibers of the superior trunk.
Correct Answer Mapping: B (Cathodal Cathode Configuration Rule).
Rationale: Cathodal stimulation is twice as efficient as anodal stimulation at inducing neural depolarization; therefore,
the negative terminal (cathode) must always be attached to the insulating block needle. A current output threshold of
0.5 mA is ideal for regional local anesthetic deposition. A persistent motor response at ≤0.2 mA indicates a
subepineural or intraneural needle tip location, which is a contraindication to injection due to structural fascicular
injury risk. Extending the pulse duration to 0.3 ms isolates sensory fibers, whereas motor mapping requires a short
0.1 ms impulse duration. 
Anesthesia Board Prep Series • Section 42: Regional Anesthesia Page 9

Question 2: While evaluating a short-axis ultrasound image of the femoral triangle, you note a
distinct structural artifact demonstrating an apparent bending of your linear block needle as it
transitions across different tissue layers. What is the underlying physical assumption violated,
and what is the corresponding name of this artifact?
A. Sound waves travel along a completely straight path; Reverberation Artifact.
B. Ultrasound waves travel through all soft tissues at a constant velocity of 1540 m/s; Bayonet
Artifact.
C. All reflecting structures are positioned along the central ray of the transducer beam; Slice Thickness
Artifact.
D. Ultrasound energy attenuates uniformly across fluid-filled cavities; Posterior Acoustic Enhancement.
Correct Answer Mapping: B (Velocity Variance Heterogeneity Rule).
Rationale: The ultrasound processing architecture converts echo arrival times into linear distance measurements
based on the rigid physical assumption that sound travels through all human soft tissues at a fixed velocity of 1540 m/
s. Local structural velocity discrepancies between lean muscle and adipose layers violate this assumption, altering the
time-to-distance conversion and causing a linear needle to appear bent on the screen—a classic manifestation known
as the Bayonet Artifact. Reverberation artifacts represent linear sound tracking reflections between parallel borders.
Slice thickness stems from off-axis beam tracking. 
Question 3: A 52-year-old male with severe chronic obstructive pulmonary disease (COPD) is
scheduled for right total shoulder arthroplasty. To minimize the incidence of hemidiaphragmatic
paralysis while ensuring effective postoperative analgesia, which of the following regional block
strategies represents the most appropriate management?
A. Perform a high-volume (30 mL) traditional interscalene brachial plexus block at the C6 level.
B. Perform a supraclavicular brachial plexus block utilizing a 25 mL volume of ropivacaine.
C. Perform a localized anterior suprascapular nerve block deep to the omohyoid muscle combined
with low-volume superior trunk targeting.
D. Proceed with a costoclavicular approach to the infraclavicular block using 40 mL of bupivacaine.
Correct Answer Mapping: C (Phrenic-Sparing Selective Target Strategy).
Rationale: Traditional interscalene blocks at the C6 level inevitably carry a 100% incidence of ipsilateral phrenic nerve
block, which can cause severe dyspnea and respiratory failure in a patient relying heavily on accessory muscles due
to severe COPD. The suprascapular nerve accounts for 70% of the structural sensory supply to the shoulder joint.
localizing the suprascapular nerve branch deep to the omohyoid muscle away from the superior trunk provides a
reliable, phrenic-sparing analgesic alternative. Supraclavicular blocks still carry a high 40-60% phrenic block risk.
Infraclavicular blocks cover the distal arm, not the shoulder joint. 
Anesthesia Board Prep Series • Section 42: Regional Anesthesia Page 10

Question 4: During a resuscitation attempt for an active cardiovascular collapse following a
presumed local anesthetic systemic toxicity (LAST) event, which of the following
pharmacological management strategies is strictly correct according to current ASRA safety
advisories?
A. Administer a standard 100 mg bolus of intravenous lidocaine for ventricular tachyarrhythmias.
B. Administer a standard 1 mg intravenous bolus of epinephrine to restore coronary perfusion pressures.
C. Avoid the administration of vasopressin and utilize Amiodarone as the first-line antiarrhythmic
agent.
D. Substitute 20% Intralipid rescue with a propofol infusion to stabilize myocardial membranes.
Correct Answer Mapping: C (ACLS Modifications for LAST Rescue).
Rationale: Resuscitation for LAST-induced cardiac arrest requires critical modifications to standard ACLS guidelines.
All local anesthetic agents (including lidocaine) are strictly omitted for arrhythmia management because they
exacerbate sodium-channel blockade toxicity. Epinephrine boluses must be severely restricted to ≤1 mcg/kg to avoid
generating severe arrhythmias, and vasopressin must be completely avoided. Amiodarone is the premier first-line
antiarrhythmic choice. Propofol is not a substitute for lipid emulsion rescue therapy; its internal lipid content is
negligible, and its potent negative inotropic properties worsen cardiovascular collapse. 
Question 5: You are selecting the optimal mid-thigh positioning parameters for an ultrasound-
guided adductor canal block. Which of the following sonoanatomical markers correctly identifies
the boundary of the "true" adductor canal and ensures proper coverage?
A. Positioning the probe immediately distal to the origin of the deep profunda femoris artery.
B. Identifying the convergence of the medial border of the sartorius muscle with the medial border
of the adductor longus muscle, isolating the double contour of the vastoadductor membrane.
C. Positioning the needle tip superficial to the vastus medialis fascial sheath to isolate pure sensory fibers.
D. Depositing a large volume (30 mL) of local anesthetic directly into the center of the sartorius muscle
belly.
Correct Answer Mapping: B (Vastoadductor Membrane Convergence Rule).
Rationale: The structural boundaries of the true adductor canal are sonographically defined by the convergence of the
medial borders of the sartorius and adductor longus muscles. The roof of this canal is composed of the thick
vastoadductor membrane, which frequently displays a characteristic double contour. Isolating this landscape is
clinically essential because the nerve to the vastus medialis (a massive contributor to total knee arthroplasty joint
pain) often travels outside the canal in its own distinct sheath. Depositing local anesthetic deep to the vastoadductor
membrane intermediate between the ASIS and patella ensures coverage of both the saphenous nerve and the nerve
to the vastus medialis while completely preserving quadriceps motor strength. Profunda femoris visualization confirms
a location that is too proximal. 
Anesthesia Board Prep Series • Section 42: Regional Anesthesia Page 11`
    }
  ]
};
